### ISSUE TITLE
Polish MCV packing logic

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#131]
In the original Red Alert 2, you can pack and move Construction Yard by simply giving a move order to the building itself:

![mcvunpack-ra2-cropped-comp](https://cloud.githubusercontent.com/assets/3705231/13010360/26965120-d1aa-11e5-915c-1f2c5fbfc382.gif)

In RA2 mod (OpenRA), you need to tell Construction Yard to pack itself and after that you can move it:

![mcvunpack-openra2-cropped-comp](https://cloud.githubusercontent.com/assets/3705231/13010364/2bba3bbc-d1aa-11e5-8e81-26ddfb17cf7a.gif)

Please pay attention to cursor icons. In RA2, the cursor indicates I can move the building. Not so in OpenRA.

OpenRA/ra2 approach is not so intuitive than seen in the original game. Additionally, I feel it's unnecessarily compilated and in a hectic battle there should be a way to tell MCV just move quickly away, not telling it first to pack itself while a player need to pay attention to the battle events at the same time. Now it feels there is an unnecessary extra command for no good reason.

**Comment by Mailaender** [comment]
That is why the game doesn't have an undeploy cursor.

**Comment by penev92** [comment]
One accidentally cancelled Nuke silo, coming up!

**Comment by GraionDilach** [comment]
Actually, this has pros and cons. A consequence of this in OpenRA is that you can finally set rallypoints for mobile war factories - in RA2 trying to set those resulted with the actual factory undeploying.

**Comment by MustaphaTR** [comment]
I think it should be settable under `Transforms:` so we can use it for CYards but modders may disable it for MWFs.

**Comment by scshunt** [comment]
It would work, I think, if you required a force-move (ALT) to do it. That would prevent accidental deploys and still allow rally points.

I think the big trouble here is the way that the conyard decides what moves are allowed. The conyard doesn't know about the movement types of the unit its becoming, and there's a lot of logic that it's not equipped to handle. We need a trait to do those calculations, but we can't easily just put one onto the conyard (what trait would that be, even? What if you have a flying MCV that uses Aircraft rather than Mobile?).

Once such a trait was written, we would then need to communicate the movement order to the newly-undeployed MCV. That would be the easier part, I think, but would still require changes to the transformation process.

**Comment by GraionDilach** [comment]
FWIW this issue should probably be moved to upstream because TS had this as well (in TS, rally points were ordered with Alt-click, which is why the two could be combined).

**Comment by Mailaender** [comment]
This was added in https://github.com/OpenRA/OpenRA/pull/16607.
