### ISSUE TITLE
Chronosphere's range should be 3x3 quadratic area, and cannot transport vehicles into ocean

### ISSUE THREAD

**Issue by Icenowy** [OpenRA/ra2#184]
Now the range is a cross of 5 vehicles, rather than 3x3 quadratic area of 9 vehicles.

In addition, currently Chronosphere cannot transport vehicles into the ocean. (In original RA2 it will make the vehicles sink if they're not amphibious)

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/pull/11624 is the first step towards the 3x3 quadratic area.

**Comment by pgwipeout** [comment]
I second this issue, noticed it today.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/pull/17786 which has been around for the last weeks.

**Comment by thennothinghappened** [comment]
Are there any plans to get this working on ra2? Looks like this functionality (at least the rectangle part) is in the engine since may 2020.
![image](https://user-images.githubusercontent.com/35243139/148665160-db3350fb-fe4a-4b84-b14d-358d162ab1e8.png)
Also if the circles for radius of the power are added (like for the nuke), it is also needed here.
