### ISSUE TITLE
Installation isn't working at all

### ISSUE THREAD

**Issue by QueenObama** [OpenRA/ra2#280]
So when I try to type "all" into the make.cmd, it tells me the builds have failed, even though I've followed the previous instructions perfectly. Is there something I'm missing? 
![failbuild](https://cloud.githubusercontent.com/assets/20609926/17076907/779dc448-508c-11e6-9cd3-4c381c0c7e55.png)

**Comment by GraionDilach** [comment]
You're using a HP desktop/laptop with preinstalled HP software. Unfortunately, one of these software adds an environment variable to Windows, tricking compilers that it's a new HPD architecture instead of x86/x64.

System->Properties->Advanced->Environment variables... and remove Platform: HPD, then retry.
