### ISSUE TITLE
can support country side yuri?

### ISSUE THREAD

**Issue by annopnod** [OpenRA/ra2#309]
open ra2 mods can support country side yuri?
![screenshot from 2016-10-29 16 01 57](https://cloud.githubusercontent.com/assets/6957642/19828504/36d27b18-9df1-11e6-9e1b-fa0c3a6d1ac9.png)

**Comment by yaaaaa** [comment]
Yes, of course OpenRA sypport any country names, and you can use models from YR (icon sprites, unit vxl files) to use it in Openra. 
But something specific for YR things, like slaveminer's slaves must change ORA engine a little, to let it works like in original game.

**Comment by Fincer** [comment]
What annopnod basically means is that RA2 mod should support Yuri faction. However, I think there are many features/logics to be implemented before this is actually possible.

Besides, there are still many basic RA2 logics which need to be polished or implemented. Once this is done I think the development process is ready for for Yuri's Revenge.

In the current state, RA2 is not even considered as an official mod for OpenRA and it's not yet included in the main OpenRA repository. Once TS (with Firestorm expansion) mod is quite mature, RA2 could get more attention (and maybe the official OpenRA mod status and moved to the official OpenRA repository). However, there are still things to be done even in basic RA1/TD/Dune mods, so... It's a long shot, anyway. Don't expect anything to happen soon, especially when talking about Yuri's Revenge.

I think the development roadmap is more or less like the following:
RA1/TD/Dune ->> TS (+ Firestorm) ->> RA2 ->> RA2 Yuri's Revenge.

And the development time? I think we are talking about years, not weeks or months.

**Comment by GraionDilach** [comment]
Most of the YR-introduced logics already exist though - BFRT's OpenTopped is basically AttackGarrisoned aka RA1 pillbox, mutations through weapon, Siege Chopper deploy is basically what OpenRA did with the TS deployers, the Genetic Mutator was basically an Ion Cannon in the code and the Dominator can be imitated with the Dune2000 deviator logic. Gattling is relatively simple to implement.

If we think strictly in YR logics (assuming all RA2 logics existing beforehand), then Magnetron would be the most challenging (due to it's weapon would need something akin to the current AreaBeam, but with strictly-target attacking, and the levitation activity), with maybe the Disc coming next (asin the leech beam). Regarding RA2, mindcontrol and spawning logic should be written with YR in mind as well (in RA2 you either controlled one or infinite units, while YR used the weapon's Damage value as cap, slaves are basically aircraft carrier planes which harvest instead of attack and doesn't die along with the spawner).

It has also been discussed IIRC that this repository will strictly go RA2 and whoever starts YR will do it in another repo. But YR itself isn't that hard, the TS and RA2 dependencies will be the problem.

**Comment by yaaaaa** [comment]
> slaves are basically aircraft carrier planes which harvest instead of attack and doesn't die along with the spawner
Thank you for this!) You just open my eyes. I'm going to make CONYARD with ability spawning eegs, and eggs wil transform in units.

**Comment by yaaaaa** [comment]
Thank you for this!) You just open my eyes. I'm going to make CONYARD with ability spawning eegs, and eggs wil transform in units.

**Comment by abcdefg30** [comment]
> It has also been discussed IIRC that this repository will strictly go RA2 and whoever starts YR will do it in another repo. But YR itself isn't that hard, the TS and RA2 dependencies will be the problem.

Yes. I'd prefer them to stay seperate.

So the answer to the question is: Yes we can support YR, but won't in the near future.
