### ISSUE TITLE
Infantry units just disappear if killed by a dog

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#328]
As the title says.

**Comment by abcdefg30** [comment]
Seems like we have to wait for https://github.com/OpenRA/OpenRA/pull/11715 to fix this.

**Comment by ibrokemypie** [comment]
now on #7506

**Comment by GraionDilach** [comment]
The solution of that ticket wouldn't help on the RA2 development, because the proposed new `AttackLeap` never would've leapt but moreso would've worked as a jousting mechanic. This is a major difference between RA1 and RA2 dog logics and while indeed upstream will need that new implementation, RA2 will need to fix the current one.

**Comment by Mailaender** [comment]
This no longer happens.
