### ISSUE TITLE
The term 'cake' is not recognized

### ISSUE THREAD

**Issue by coolrecep** [OpenRA/ra2#343]
I have downloaded cake and added it as a System Variable but I am getting this error when I run make.cmd.

`cake : The term 'cake' is not recognized as the name of a cmdlet, function, scr
ipt file, or operable program. Check the spelling of the name, or if a path was
 included, verify that the path is correct and try again.
At C:\Users\Recep\Documents\OpenRA\mods\ra2\make.ps1:32 char:1
+ cake -target="$command"
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (cake:String) [], CommandNotFoun
   dException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\Users\Recep\Documents\OpenRA\mods\ra2>PAUSE
Press any key to continue . . .`

![image](https://cloud.githubusercontent.com/assets/13221472/21462123/f2699768-c960-11e6-86f5-84c7ef184c2c.png)

**Comment by coolrecep** [comment]
Oh and this is what I get when I type cake at CMD:

![image](https://cloud.githubusercontent.com/assets/13221472/21462213/0159254e-c962-11e6-91d4-5afa6a1a5954.png)

**Comment by Mailaender** [comment]
@Phrohdoh can probably help with this.

**Comment by Phrohdoh** [comment]
@coolrecep Close all instances of CMD / PS then open a new instance of PowerShell.
`cd` into the root directory of the `ra2` you cloned.

Then `cake` should work as expected.

Your second screenshot shows that this was a new CMD instance so that explains why cake is found on your %PATH% there (environment variables aren't reloaded until a restart of CMD/PS).

**Comment by Mailaender** [comment]
Assuming this is resolved.

**Comment by coolrecep** [comment]
Solve by using the latest Cake-bin-net45-v0.17.0.
