### ISSUE TITLE
Missing Power Bar

### ISSUE THREAD

**Issue by ibrokemypie** [OpenRA/ra2#363]
The Power Bar on the left of the construction ui is empty, meaning it is not possible to know power usage.

**Comment by MustaphaTR** [comment]
Power usage is currently written in numbers instead of a bar. It is currently not supported to have a power bar near building UI,which needs to longen with UI itself if there are much to build.

Power Bar near Minimap as in TD mod is supported but it wouldn't work here.

**Comment by pchote** [comment]
> It is currently not supported to have...

Sure it is.  There is nothing stopping you from adding a small `ChromeLogic` class to your Mods.RA2 dll that adjusts the bar height to match the sidebar height.

**Comment by GraionDilach** [comment]
I think noone shares your definition of "support" @pchote.

**Comment by pchote** [comment]
No one would say that black hawks don't "support" damage in #362, because the fix for that involves changing the ra2 mod yaml and doesn't depend on the upstream engine or common mod logic.

Likewise, the fix for this involves changing the ra2 mod C#, and doesn't depend on the upstream engine or common mod logic.  If a mod wants custom UI then we have a stable API to support that.

You know better than anyone (as the main person providing this "support") that mods that take a "someone else will do all my c# changes for me" mindset are going to be artificially limiting themselves through no fault of the upstream OpenRA/OpenRA project.

**Comment by MustaphaTR** [comment]
> There is nothing stopping you

I couldn't get the RA2 mod the start, to be more exact to install the cake. But as it is not in fromt of my priotiry list. I didn't care much. I actually have some stuff to do with RA2 mod (Rocketter fall to ground, i did it for my D2K mod already). If it is really as easy as you make it sound like i can take a look to this too.

**Comment by rob-v** [comment]
@MustaphaTR Cake on Windows or Linux?
On Windows I didn't need to install it:
1. download and extract https://github.com/cake-build/cake/releases/download/v0.13.0/Cake-bin-v0.13.0.zip
2. right click \Documents\OpenRA\mods\ra2\build.cake, Open with.. locate Cake.exe

**Comment by Mailaender** [comment]
This was added in https://github.com/OpenRA/ra2/pull/595.
