### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by jrb0001** [OpenRA/ra2#379]
The C# code is obviously under GPL3+ but the situation is unclear for the .yaml's and other stuff like the uibits.

**Comment by Iamgoofball** [comment]
GPL is infectious to other files.

**Comment by abcdefg30** [comment]
What I got from the discussion on IRC was that the license does apply to the `.yaml` files as well.

**Comment by jrb0001** [comment]
@abcdefg30 and what about the uibits and other images?

**Comment by abcdefg30** [comment]
Most of them are taken from OpenRA or made by @x-a-n-a-x. I wanted to talk to him before I add the copying file.

**Comment by x-a-n-a-x** [comment]
Where to start..
I don't think it's possible to say that uibits are under GPL or even, under one of these permissive Creative Commons licenses.

To create this RA2 UI (and the D2K UI, and the TS UI as well), I used parts of the original UI and because of the three-column production palette OpenRA features, I had to modify some areas on the sidebar. 

If you compare the OpenRA UIs (well, the ones that I did) with the original UIs, you can spot the differences. These changes (modifications) were made by me, from scratch. So what we have in OpenRA is a mix of the two.

But because I used the original UIs (as a base) for this "art-work", we can't add a GPL/Creative Commons License on these uibits images (IMO).

Maybe we should do what pchote did for the RA1 UI : create an original interface from scratch, not related at all to the old UIs.
