### ISSUE TITLE
New Option for Utility.exe --import-ra2-map

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#380]
I think we need map import support for Red Alert 2 so that we can import maps from original Red Alert 2

**Comment by Fincer** [comment]
Yeah, would be nice to have.

I have written a lazy/multi-step guide for importing RA2 maps into OpenRA (see the link below).

https://github.com/Fincer/openra-ra2-mappack

However, it still uses import-ts-map option. I have tested it in the last year, and technically, it worked.

**Comment by GraionDilach** [comment]
The RA2 maps don't need a separate command, because RA2 uses the TS map format, so the import-ts-map is more than sufficient for this job. Technically RA2 only removed aud support in favor of wav and bag/idx and vqa support in favor of bik. Everything else is formatwise the same (map format, terrain definition format, shp/voxel formats).

The sole reason there might be a need for import-ra2-map is that Westwood pulled a strong stupid there by masking the third type of the resource to look the same as first type of ore which then got this third type of resource used on some maps instead of the first but the map editor converts everything but the first resource to the second one - this is the reason why some maps like IIRC DEFCON-6 or A Path Beyond II ended up with gems instead of ore. However, hardcoding this substitution is also wrong because a good amount of thirdparty RA2 mods actually fixed this and then used the third resource for their needs.

**Comment by abcdefg30** [comment]
Well, seems like there is no need for a new command at the moment.
