### ISSUE TITLE
US Spy Sat doesn't seem to work.

### ISSUE THREAD

**Issue by beigexperience** [OpenRA/ra2#406]
You might know this already but the spy sat radar map revealer of the Americans doesn't seem to work. 

I have absolutely no idea what I'm doing but changing the basic `RevealsShroud` Range to a big number seems to mimick the desired effect until it bumps up against `MaximumTileSearchRange` from `OpenRA.Game/Map/MapGrid.cs`. This is probably not the proper solution.

I've just started reading through the code, but as far as I understand you'd want to encapsulate the shroud revealing logic in some sort of "trait" I guess you call it that's invoked on power gained to the building/power loss right?

**Comment by abcdefg30** [comment]
We probably want to abuse the `GPSPower` or create a similar trait, yes.

**Comment by GraionDilach** [comment]
Do note that fog of war is the reason why RA1 got GPS icons instead of the full-map-reveal it had. I'm not sure if recreating the shroud/FoW removal entirely wiith spysats would be good.

**Comment by beigexperience** [comment]
Hmm, the visual studio .sln solution file seems to be broken?

**Comment by Nihilianth** [comment]
It seems to me like this one can only be fixed with changes to Shroud.cs in  OpenRA (e.g. splitting the disable flag to work for shroud and fog separately or adding a new SourceType). It seems impossible atm to temporarily disable the shroud without also disabling fog of war and affecting exploration data permanently.

**Comment by sorcerer86pt** [comment]
Well in RA2 OG, GPS satellite it would reveal all, and it was a major advantage in both single and multiplayer game. I don't know if OpenRA decided to GPS icons for multiplayer balance, or if it was like that in the original RA game. 

RA2 GPS had it's shortcomings and advantages of course in relation to RA1. Since it was based on a building, it was deployed instantly if we had the energy for it, but if it was not powered or destroyed that effect was disabled. 
In RA1 we had to wait to finish deploying the satellite, but if the tech center was destroyed, the effect was still in usage, as long we had the radar some. 

https://cnc.fandom.com/wiki/Global_Positioning_System

IMHO,  aside from a balance issue, we should mantain the OG behavior.

In relation to implementation, the spy satellite building should have a trait, that as long the building was powered, it revealed all fog and map. This would implement the OG behavior, mantain some balance and encapsulated the behavior for other mods.

**Comment by GraionDilach** [comment]
Westwood had no implementation of fog of war before TS and even the implementation within TS/RA2 was broken, which is why they were disabled entirely, with only the sprite remaining among the shipped assets.

WW RA2 reshrouded the map when the SpySat was lost, exactly the way a Spy infiltration would have.

**Comment by sorcerer86pt** [comment]
First part, I didn't even knew that.
The second, yeah, that completely true.

**Comment by sorcerer86pt** [comment]
anyone will do anything on this issue?

**Comment by ShikiSuen** [comment]
US Spy Sat can be used as a tertiary superweapon:

Everytime using it, the user can see the entire maps explosed as a static snapshot for 15 seconds (except explosed area).

**Comment by Shin-Aska** [comment]
We may have to wait a little bit before we can take action on this. @Mailaender's patch is not yet included on release **20200503** 😞

**Comment by beigexperience** [comment]
So was the RA2 US sat implemented? Should this be closed? Also happy new year.

**Comment by Mailaender** [comment]
The base engine was updated, but the new trait was not yet added: https://github.com/OpenRA/ra2/pull/802
