### ISSUE TITLE
Consider creating a CI build on Azure DevOps

### ISSUE THREAD

**Issue by oising** [OpenRA/ra2#570]
It's free (infinite build minutes) for open source projects. This might get more eyes on it.

**Comment by MustaphaTR** [comment]
Please create issues related to SDK to https://github.com/OpenRA/OpenRAModSDK.

**Comment by GraionDilach** [comment]
Incorporating a new CI should be first done in OpenRA/OpenRA anyway. Which probably has no need for more CIs, since Travis-CI and AppVeyor is already functional and cover all needs (sans Coverity, since Coverity integration broke years ago on AppVeyor).

Incorporating a new CI for "advertising reasoning" does not sound like a practical benefit.

Looking around on GH at various other game recreation projects, it is true that OpenTTD uses Azure but most other projects I'm aware of (VCMI, ioquake3(-derivates), OpenRCT2) uses Travis/AppVeyor combination. The reasoning behind OpenTTD sticking out as a sore thumb is because it switched to Azure from _Jenkins_, an artifact from their pre-GitHub architecture while the rest have been started out/moved years ago to GH with deploying the de facto standard CIs by then.
