### ISSUE TITLE
Using Github Actions to build Binaries

### ISSUE THREAD

**Issue by saikek** [OpenRA/ra2#751]
Is absence of binary file - some kind of license issue or it's just a matter of not having enought time to automate it ? 
The only way to use OpenRA/RA2 now is to download and build manually.

It should not be hard to create `Github Actions` script to build binaries for all OS's and share them on actions/artifacts page or on releases.

What do you think ?

**Comment by abcdefg30** [comment]
That is intentional. This mod is far from being in a state to show it off, so we don't want to give the impression it is something playable by providing binaries. This is also the policy used for TS in the upstream repository. Moving to GitHub Actions over Travis is a good idea, and we will do that once OpenRA/OpenRA has transitioned too. (The current plan is to finish moving that to .NET core and then use GitHub Actions; then this repo can follow.)
